
# coding: utf-8

import pandas as pd
import numpy as np


print("Loading post 2008 data...")
post08 = pd.read_csv('H1B_post2008_data.csv', encoding="ISO-8859-1", dtype=str, index_col=0)
print("Post 2008 file loading complete. Dataframe shape is ",post08.shape)

print("Loading and appending pre-2008 fax data...")
from zipfile import ZipFile
for i in range(1, 7):
        print('\t Reading and appending fax data from 200{}'.format(i))
        with ZipFile('/'.join(['raw_data', 'H1B_fax_FY200{}_text.zip'.format(i)])) as zip_file:
            filename=''
            if i in [1,3,5]:
                filename='H1B_Fax_FY200{}_Download.txt'.format(i)
                columns = ['CASE_NUMBER','CASE_STATUS','RETURN_FAX','EMPLOYER_NAME','EMPLOYER_CITY','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','WAGE_RATE_OF_PAY_FROM','WAGE_RATE_OF_PAY_TO','WAGE_UNIT_OF_PAY','PART_TIME','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','SOC_CODE','TOTAL_WORKERS','JOB_TITLE','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_UNIT_OF_PAY','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_UNIT_OF_PAY_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','DECISION_DATE','PROCESS_DATE']
            elif i==2: 
                filename='H1B_FAX_FY200{}_Download.txt'.format(i)
                columns = ['CASE_NUMBER','CASE_STATUS','RETURN_FAX','EMPLOYER_NAME','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','WAGE_RATE_OF_PAY_FROM','WAGE_RATE_OF_PAY_TO','WAGE_UNIT_OF_PAY','PART_TIME','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','SOC_CODE','TOTAL_WORKERS','JOB_TITLE','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_UNIT_OF_PAY','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_UNIT_OF_PAY_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','DECISION_DATE','PROCESS_DATE']
            elif i==4:
                filename='H1B_fax_FY0{}.txt'.format(i)
                columns = ['CASE_NUMBER','CASE_STATUS','RETURN_FAX','EMPLOYER_NAME','EMPLOYER_CITY','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','WAGE_RATE_OF_PAY_FROM','WAGE_RATE_OF_PAY_TO','WAGE_UNIT_OF_PAY','PART_TIME','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','SOC_CODE','TOTAL_WORKERS','JOB_TITLE','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_UNIT_OF_PAY','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_UNIT_OF_PAY_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2','FIRST_NAME_SIGNED','LAST_NAME_SIGNED','TITLE_SIGNED','DATE_SIGNED','CONTACT_FIRST_NAME','CONTACT_LAST_NAME','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','DECISION_DATE','PROCESS_DATE']
            elif i==6:
                filename='H1B_Fax_FY200{}_External_Web.txt'.format(i)
                columns = ['CASE_NUMBER','CASE_STATUS','RETURN_FAX','EMPLOYER_NAME','EMPLOYER_CITY','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','WAGE_RATE_OF_PAY_FROM','WAGE_RATE_OF_PAY_TO','WAGE_UNIT_OF_PAY','PART_TIME','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','SOC_CODE','TOTAL_WORKERS','JOB_TITLE','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_UNIT_OF_PAY','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_UNIT_OF_PAY_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2','DATE_SIGNED','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','DECISION_DATE','PROCESS_DATE']
            with zip_file.open(filename) as file:
                    data = pd.read_csv(file, dtype=str, encoding='Latin-1')
                    data.columns=columns
                    post08 = post08.append(data, ignore_index=True)
                    print("\t Loading complete, shape is now ",post08.shape)
                        


print("Loading and appending pre-2008 e-file data...")
for i in range(2,8):
    print('\t Reading and appending e-file data from 200{}'.format(i))
    with ZipFile('/'.join(['raw_data', 'H1B_efile_FY0{}_text.zip'.format(i)])) as zip_file:
        if i in [2,3,4,6]:
            filename='H1B_efile_FY0{}.txt'.format(i)
            columns = ['CASE_SUBMITTED','CASE_NUMBER','EMPLOYER_NAME','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','TOTAL_WORKERS','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','JOB_TITLE','DECISION_DATE','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','SOC_CODE','CASE_STATUS','WAGE_RATE_OF_PAY_FROM','WAGE_UNIT_OF_PAY','WAGE_RATE_OF_PAY_TO','PART_TIME','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WAGE_RATE_OF_PAY_2','WAGE_UNIT_OF_PAY_2','MAX_RATE_2','PART_TIME_2','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2']
        elif i == 5:
            filename='H1B_FY0{}_Efile.txt'.format(i)
            columns = ['CASE_SUBMITTED','CASE_NUMBER','EMPLOYER_NAME','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','TOTAL_WORKERS','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','JOB_TITLE','DECISION_DATE','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','SOC_CODE','SIGNER_FIRST','SIGNER_LAST','SIGNERR_POSITION','OTHER_FIRST','OTHER_LAST','CASE_STATUS','WAGE_RATE_OF_PAY_FROM','WAGE_UNIT_OF_PAY','WAGE_RATE_OF_PAY_TO','PART_TIME','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WAGE_RATE_OF_PAY_2','WAGE_UNIT_OF_PAY_2','MAX_RATE_2','PART_TIME_2','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2']
        elif i == 7: 
            filename='EFILE_FY200{}.txt'.format(i)
            columns = ['CASE_SUBMITTED','CASE_NUMBER','VISA_CLASS','EMPLOYER_NAME','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','TOTAL_WORKERS','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','JOB_TITLE','DECISION_DATE','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','SOC_CODE','CASE_STATUS','WAGE_RATE_OF_PAY_FROM','WAGE_UNIT_OF_PAY','WAGE_RATE_OF_PAY_TO','PART_TIME','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WAGE_RATE_OF_PAY_2','WAGE_UNIT_OF_PAY_2','MAX_RATE_2','PART_TIME_2','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2','WITHDRAWN']

        with zip_file.open(filename) as file:
            if i == 5:
                data = pd.read_csv(file, dtype=str, encoding='Latin-1', header=None)
            else:
                data = pd.read_csv(file, dtype=str, encoding='Latin-1')
            data.columns=columns
            post08 = post08.append(data, ignore_index=True)
            if i == 4:
                with zip_file.open('H1B_efile_FY0{}.txt'.format(i + 1)) as file:
                    data = pd.read_csv(file, dtype=str, encoding='Latin-1')
                    columns = ['CASE_SUBMITTED','CASE_NUMBER','EMPLOYER_NAME','EMPLOYER_ADDRESS1','EMPLOYER_ADDRESS2','EMPLOYER_CITY','EMPLOYER_STATE','EMPLOYER_POSTAL_CODE','TOTAL_WORKERS','EMPLOYMENT_START_DATE','EMPLOYMENT_END_DATE','JOB_TITLE','DECISION_DATE','CERTIFICATION_START_DATE','CERTIFICATION_END_DATE','SOC_CODE','CASE_STATUS','WAGE_RATE_OF_PAY_FROM','WAGE_UNIT_OF_PAY','WAGE_RATE_OF_PAY_TO','PART_TIME','WORKSITE_CITY','WORKSITE_STATE','PREVAILING_WAGE','PW_WAGE_SOURCE','PW_SOURCE_YEAR','PW_SOURCE_OTHER','WAGE_RATE_OF_PAY_2','WAGE_UNIT_OF_PAY_2','MAX_RATE_2','PART_TIME_2','WORKSITE_CITY_2','WORKSITE_STATE_2','PREVAILING_WAGE_2','PW_WAGE_SOURCE_2','PW_SOURCE_YEAR_2','PW_WAGE_SOURCE_OTHER_2']
                    data.columns=columns
                    post08 = post08.append(data, ignore_index=True)
            print("\t Loading complete, shape is now ",post08.shape)
print("Writing final csv file...")
post08.to_csv('H1B_Full_Data.csv',encoding='utf-8')
print("Complete.")
